Add FAQ
pixee/pixee-cli pull request #4
Opened 2023-12-13 21:28 UTC by drdavella

2023-12-13 22:00 UTC, nahsra requested changes

2023-12-14 02:03 UTC, drdavella commented on README.md
> +
I think this feature needs to be opt-in from the CLI (for codemodder too) and we should be explicit about when it occurs. I don't think we can assume just because an `OPENAI_API_KEY` is defined that the user is okay with us spending their money and/or sending their code implicitly. Also I don't think we want to be specific about a particular vendor here since we may at some point send data to other vendors and/or our own services.

2023-12-14 05:11 UTC, nahsra commented on README.md
> +
> we should be explicit about when it occurs. I don't think we can assume just because an OPENAI_API_KEY

Do you take it as implied consent if we only honor a `PIXEE_OPENAI_API_KEY`?

> Also I don't think we want to be specific about a particular vendor here since we may at some point send data to other vendors and/or our own services.

I've seen lots of sites now that ask me to acknowledge OpenAI as a subprocessor and consent to sending data to them.

2023-12-14 14:54 UTC, drdavella commented on README.md
> +
Yes that feels more like a proper opt-in to me. Is it okay to keep this text relatively general for now and then update to mention OpenAI later once those features are available?

2023-12-14 18:41 UTC, drdavella commented
I'm taking the liberty of merging this PR (with new updates) but we can make additional changes at any point.

2023-12-14 18:41 UTC, merged